#index:
#    path: /
#    controller: App\Controller\DefaultController::index
admin:
  path: /admin 
  controller: App\Controller\AdminController::admin

api_login_check:
  path: /login

authentication_token:
    path: /login
    methods: ['POST']
gesdinet_jwt_refresh_token:
    path: /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh